var portfolio_details_datas = [
    {
        "portfolio__details_two_title" : "Worksimply Hub",
        "portfolio__details_two_text-1" : "A Worksimply Hub is a unique concept that transforms restaurants in downtown Toronto into vibrant coworking spaces. Each day of the week, we gather at different restaurants (Worksimply Hubs) to provide professionals with a dynamic and collaborative work environment.",
        "portfolio__details_two_text-2" : "Our mission is clear: provide a space where remote workers can come together, connect over delicious food, and forge lasting relationships beyond the confines of work.",
        // "portfolio__details_two_client" : "ThemeOri agency1",
        // "portfolio__details_two_category" : "Brochure Design2",
        // "portfolio__details_two_date" : "27 March, 2022",
        "portfolio__details_two_url" : "https://worksimply.com/",
        "portfolio__details_two_sitename" : "worksimply.com",
        "portfolio__details_two_img1" : "assets/img/portfoli/portfolio-1-1.png",
        "portfolio__details_two_img2" : "assets/img/portfoli/portfolio-1-2.png",
        "portfolio__details_two_img3" : "assets/img/portfoli/portfolio-1-3.png",
        "portfolio__details_two_img4" : "assets/img/portfoli/portfolio-1-4.png",
    },
    {
        "portfolio__details_two_title" : "Highest Quality Peptides for Sale",
        "portfolio__details_two_text-1" : "We are proud to carry the highest quality peptides and peptide blends in the research industry.",
        "portfolio__details_two_text-2" : "We are a leading provider of high-quality peptides for laboratories, researchers, and academic institutions across the globe. All our products are synthesized and lyophilized in the United States, with purity levels exceeding 99%+. We have a wide offering of standard peptides as well as topical peptides, peptide blends, customizable orders, and an expert team ready to assist you.",
        // "portfolio__details_two_client" : "ThemeOri agency1",
        // "portfolio__details_two_category" : "Brochure Design2",
        // "portfolio__details_two_date" : "27 March, 2022",
        "portfolio__details_two_url" : "https://www.corepeptides.com/",
        "portfolio__details_two_sitename" : "corepeptides.com",
        "portfolio__details_two_img1" : "assets/img/portfoli/portfolio-2-1.png",
        "portfolio__details_two_img2" : "assets/img/portfoli/portfolio-2-2.png",
        "portfolio__details_two_img3" : "assets/img/portfoli/portfolio-2-3.png",
        "portfolio__details_two_img4" : "assets/img/portfoli/portfolio-2-4.png",
    },
    {
        "portfolio__details_two_title" : "The Quest for Counsel Starts Here",
        "portfolio__details_two_text-1" : "Find High-Quality Lawyers By Practice Area",
        "portfolio__details_two_text-2" : "Our attorney-managed consultation service connects you with high-quality lawyers that focus on your specific type of legal case.",
        // "portfolio__details_two_client" : "ThemeOri agency1",
        // "portfolio__details_two_category" : "Brochure Design2",
        // "portfolio__details_two_date" : "27 March, 2022",
        "portfolio__details_two_url" : "https://counselhound.com/",
        "portfolio__details_two_sitename" : "counselhound.com",
        "portfolio__details_two_img1" : "assets/img/portfoli/portfolio-3-1.png",
        "portfolio__details_two_img2" : "assets/img/portfoli/portfolio-3-2.png",
        "portfolio__details_two_img3" : "assets/img/portfoli/portfolio-3-3.png",
        "portfolio__details_two_img4" : "assets/img/portfoli/portfolio-3-4.png",
    },
    {
        "portfolio__details_two_title" : "The Development Tracker",
        "portfolio__details_two_text-1" : "The Development Tracker stands to serve as a comprehensive and indispensable platform within the real estate development landscape, revolutionizing the way stakeholders and citizens engage with and perceive real estate development.",
        "portfolio__details_two_text-2" : "Our pioneering approach redefines the conventional scope by providing a multifaceted suite of services curated to make powerful connections that have never been exhibited before and to drive success within virtually every facet of the real estate development realm.",
        // "portfolio__details_two_client" : "ThemeOri agency1",
        // "portfolio__details_two_category" : "Brochure Design2",
        // "portfolio__details_two_date" : "27 March, 2022",
        "portfolio__details_two_url" : "https://thedevelopmenttracker.com/",
        "portfolio__details_two_sitename" : "TheDevelopmentTracker.com",
        "portfolio__details_two_img1" : "assets/img/portfoli/portfolio-4-1.png",
        "portfolio__details_two_img2" : "assets/img/portfoli/portfolio-4-2.png",
        "portfolio__details_two_img3" : "assets/img/portfoli/portfolio-4-3.png",
        "portfolio__details_two_img4" : "assets/img/portfoli/portfolio-4-4.png",
    },
    {
        "portfolio__details_two_title" : "GAST HOMES",
        "portfolio__details_two_text-1" : "Gulf Beach Development, Inc",
        "portfolio__details_two_text-2" : "From the time you sit down with Gast Homes to discuss your dream home to the moment you open the door of your newly completed custom Florida home you'll be ready for pure excitement.  We specialize in helping you design the home to match your lifestyle.",
        // "portfolio__details_two_client" : "ThemeOri agency5",
        // "portfolio__details_two_category" : "Brochure Design5",
        // "portfolio__details_two_date" : "27 March, 2022",
        "portfolio__details_two_url" : "https://gasthomes.com/",
        "portfolio__details_two_sitename" : "gasthomes.com",
        "portfolio__details_two_img1" : "assets/img/portfoli/portfolio-5-1.png",
        "portfolio__details_two_img2" : "assets/img/portfoli/portfolio-5-2.png",
        "portfolio__details_two_img3" : "assets/img/portfoli/portfolio-5-3.png",
        "portfolio__details_two_img4" : "assets/img/portfoli/portfolio-5-4.png",
    },
    {
        "portfolio__details_two_title" : "Oncie, the live audio app",
        "portfolio__details_two_text-1" : "The live audio app that pushes your voice to a new dimension",
        "portfolio__details_two_text-2" : "Did you ever want to invite someone on your show ? Planning a remote interview or letting a listener join you on air is now possible thanks to the multi-live feature.",
        // "portfolio__details_two_client" : "ThemeOri agency1",
        // "portfolio__details_two_category" : "Brochure Design2",
        // "portfolio__details_two_date" : "27 March, 2022",
        "portfolio__details_two_url" : "https://oncie.live/en",
        "portfolio__details_two_sitename" : "oncie.live/en",
        "portfolio__details_two_img1" : "assets/img/portfoli/portfolio-6-1.png",
        "portfolio__details_two_img2" : "assets/img/portfoli/portfolio-6-2.png",
        "portfolio__details_two_img3" : "assets/img/portfoli/portfolio-6-3.png",
        "portfolio__details_two_img4" : "assets/img/portfoli/portfolio-6-4.png",
    },
    {
        "portfolio__details_two_title" : "Boys & Girls Clubs",
        "portfolio__details_two_text-1" : "Imagine a place where the circumstances that surround you don't determine your access to opportunities. Boys & Girls Clubs are making that vision a reality—in our community and communities around the world.",
        "portfolio__details_two_text-2" : "We're committed to enabling all young people, especially those who need us most, to reach their full potential as productive, caring, responsible citizens.",
        // "portfolio__details_two_client" : "ThemeOri agency1",
        // "portfolio__details_two_category" : "Brochure Design2 777",
        // "portfolio__details_two_date" : "27 March, 2022",
        "portfolio__details_two_url" : "https://www.bgclubspringfield.org/",
        "portfolio__details_two_sitename" : "www.bgclubspringfield.org",
        "portfolio__details_two_img1" : "assets/img/portfoli/portfolio-7-1.png",
        "portfolio__details_two_img2" : "assets/img/portfoli/portfolio-7-2.png",
        "portfolio__details_two_img3" : "assets/img/portfoli/portfolio-7-3.png",
        "portfolio__details_two_img4" : "assets/img/portfoli/portfolio-7-4.png",
    },
    {
        "portfolio__details_two_title" : "Lust a Hair!",
        "portfolio__details_two_text-1" : "Luxury 100% Remy Human Hair Toppers. The perfect solution for volume, coverage and style. Global Online Retailer 🇺🇸🇦🇺🇬🇧🇨🇦🇪🇺",
        "portfolio__details_two_text-2" : "Find your prefect piece! Book your free virtual chat!",
        // "portfolio__details_two_client" : "ThemeOri agency1",
        // "portfolio__details_two_category" : "Brochure Design2",
        // "portfolio__details_two_date" : "27 March, 2022 888",
        "portfolio__details_two_url" : "https://lustahair.com/",
        "portfolio__details_two_sitename" : "lustahair.com",
        "portfolio__details_two_img1" : "assets/img/portfoli/portfolio-8-1.png",
        "portfolio__details_two_img2" : "assets/img/portfoli/portfolio-8-2.png",
        "portfolio__details_two_img3" : "assets/img/portfoli/portfolio-8-3.png",
        "portfolio__details_two_img4" : "assets/img/portfoli/portfolio-8-4.png",
    },
    {
        "portfolio__details_two_title" : "Calmind.com",
        "portfolio__details_two_text-1" : "A digital therapy software which will improve your quality of life.",
        "portfolio__details_two_text-2" : "By combining elements of neuroscience, psychoacoustics, positive CBT, and technology, we've created an entirely new kind of treatment that provides physiological and stress-reducing benefits to each of your senses.",
        // "portfolio__details_two_client" : "ThemeOri agency1",
        // "portfolio__details_two_category" : "Brochure Design2",
        // "portfolio__details_two_date" : "27 March, 2022",
        "portfolio__details_two_url" : "https://calmind.com/",
        "portfolio__details_two_sitename" : "calmind.com",
        "portfolio__details_two_img1" : "assets/img/portfoli/portfolio-9-1.png",
        "portfolio__details_two_img2" : "assets/img/portfoli/portfolio-9-2.png",
        "portfolio__details_two_img3" : "assets/img/portfoli/portfolio-9-3.png",
        "portfolio__details_two_img4" : "assets/img/portfoli/portfolio-9-4.png",
    },
    {
        "portfolio__details_two_title" : "Virtual Staging Furniture",
        "portfolio__details_two_text-1" : "Choose from our predesigned sets or let our designers choose for you. All furniture can be resized, color changed, and adapted to different layouts.",
        "portfolio__details_two_text-2" : "We're here to make home buying more informed and inspiring for everyone.",
        // "portfolio__details_two_client" : "ThemeOri agency1",
        // "portfolio__details_two_category" : "Brochure Design2",
        // "portfolio__details_two_date" : "27 March, 2022",
        "portfolio__details_two_url" : "https://virtualstagingsolutions.com/",
        "portfolio__details_two_sitename" : "virtualstagingsolutions.com",
        "portfolio__details_two_img1" : "assets/img/portfoli/portfolio-10-1.png",
        "portfolio__details_two_img2" : "assets/img/portfoli/portfolio-10-2.png",
        "portfolio__details_two_img3" : "assets/img/portfoli/portfolio-10-3.png",
        "portfolio__details_two_img4" : "assets/img/portfoli/portfolio-10-4.png",
    },
    {
        "portfolio__details_two_title" : "BEST WINDOWS & DOORS",
        "portfolio__details_two_text-1" : "Let's Meet The South Florida Window & Door Professionals.",
        "portfolio__details_two_text-2" : "Carbonneau's may be the name on the truck, but the Shea family has been at the helm of this family-owned business since 2001. Under ownership of Michael Shea, Carbonneau's has become South Florida's top window and door installation company by consistently delivering quality workmanship, timely completion, competitive pricing, and exceptional customer service at every stage along the way.",
        // "portfolio__details_two_client" : "ThemeOri agency1",
        // "portfolio__details_two_category" : "Brochure Design2",
        // "portfolio__details_two_date" : "27 March, 2022",
        "portfolio__details_two_url" : "https://www.carbonneauswindowsanddoors.com/",
        "portfolio__details_two_sitename" : "www.carbonneauswindowsanddoors.com",
        "portfolio__details_two_img1" : "assets/img/portfoli/portfolio-11-1.png",
        "portfolio__details_two_img2" : "assets/img/portfoli/portfolio-11-2.png",
        "portfolio__details_two_img3" : "assets/img/portfoli/portfolio-11-3.png",
        "portfolio__details_two_img4" : "assets/img/portfoli/portfolio-11-4.png",
    },
    {
        "portfolio__details_two_title" : "RedLine",
        "portfolio__details_two_text-1" : "Pass Your Limits With Redline.",
        "portfolio__details_two_text-2" : "Here at Redline, we are dedicated to providing you with the most high quality email marketing solutions and short-term working capital leads available on the market today.",
        // "portfolio__details_two_client" : "ThemeOri agency1",
        // "portfolio__details_two_category" : "Brochure Design2",
        // "portfolio__details_two_date" : "27 March, 2022",
        "portfolio__details_two_url" : "https://www.chooseredline.com/",
        "portfolio__details_two_sitename" : "www.chooseredline.com",
        "portfolio__details_two_img1" : "assets/img/portfoli/portfolio-12-1.png",
        "portfolio__details_two_img2" : "assets/img/portfoli/portfolio-12-2.png",
        "portfolio__details_two_img3" : "assets/img/portfoli/portfolio-12-3.png",
        "portfolio__details_two_img4" : "assets/img/portfoli/portfolio-12-4.png",
    }
];

const details_index = parseInt(localStorage.getItem("portfolio__area-two-current-index"));
const content_data = portfolio_details_datas[details_index];
for (const key in content_data) {
    const element = content_data[key];
    if (key == "portfolio__details_two_url") {
        document.getElementById("portfolio__details_two_page_link").href = element;
    } else if (key == "portfolio__details_two_sitename") {
        document.getElementById("portfolio__details_two_page_link").innerText = element;
        // alert(element + document.getElementById("portfolio__details_two_page_link").innerText);
    } else if (key.substring(0, key.length - 1).endsWith("_img")) {
        document.getElementById(key).src = element;
    } else {
        document.getElementById(key).innerText = element;
    }
}
